"""Generate src/04g2-material.js: Google Material Symbols grouped by category.

Names and categories come from Google Fonts' icon metadata; only icons that
exist in the pinned @material-symbols/svg-400 release are kept, so every
catalog entry resolves to an SVG on jsDelivr.

Usage: python tools/build_material.py
"""
import json, os, urllib.request

VERSION = "0.47.4"  # @material-symbols/svg-400, pinned
META = "https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true"
NAMES = f"https://cdn.jsdelivr.net/npm/@material-symbols/metadata@{VERSION}/versions.json"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "04g2-material.js")


def get(url):
    with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": "glc-build"})) as r:
        return r.read().decode("utf8")


def main():
    raw = get(META)
    meta = json.loads(raw[raw.index("{"):])
    available = set(json.loads(get(NAMES)).keys())
    groups = {}
    for ic in meta["icons"]:
        name = ic["name"]
        if name not in available:
            continue
        if "Material Symbols Outlined" in ic.get("unsupported_families", []):
            continue
        cat = (ic.get("categories") or ["other"])[0].replace("&", " and ").replace("_", " ")
        cat = " ".join(cat.split()).capitalize().replace("Ui ", "UI ")
        groups.setdefault(cat, []).append(name)
    groups = {k: sorted(v) for k, v in sorted(groups.items())}
    total = sum(len(v) for v in groups.values())
    data = {
        "label": "Google",
        "title": "Material Symbols",
        "license": "Apache-2.0",
        "url": f"https://cdn.jsdelivr.net/npm/@material-symbols/svg-400@{VERSION}/{{name}}.svg",
        "styles": ["outlined", "rounded", "sharp"],
        "groups": groups,
    }
    with open(OUT, "w", encoding="utf8", newline="\n") as f:
        f.write("// ---------------------------------------------------------------- Google Material Symbols (generated by tools/build_material.py)\n")
        f.write(f"// {total} icons, Apache-2.0, served by jsDelivr from @material-symbols/svg-400@{VERSION}\n")
        f.write("CATALOG.iconSets.google = " + json.dumps(data, separators=(",", ":")) + ";\n")
    print("wrote", OUT, total, "icons in", len(groups), "categories", os.path.getsize(OUT), "bytes")


main()
